# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-16 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('message', models.CharField(max_length=500, verbose_name='信息')),
            ],
            options={
                'verbose_name': '留言版',
                'verbose_name_plural': '留言版',
            },
        ),
    ]
